### ISSUE TITLE
neat lag

### ISSUE THREAD

**Issue by KibaTheBarbarian** [kotmatross28729/Neat-shaders-fix#3]
with the mod it fixed some of neat bug like going in f5 etc but it lags unlike the old ver but your ver lags with [Angelica](https://github.com/GTNewHorizons/Angelica/releases/tag/1.0.0-beta4) old ver don't a vid showing it [neat lag](https://clips.twitch.tv/CredulousHealthyCaterpillarCorgiDerp-gGRxekKf3W5ETAZp)

Mod list
[Angelica](https://github.com/GTNewHorizons/Angelica/releases/tag/1.0.0-beta4)
[your neat](https://github.com/kotmatross28729/Neat-shaders-fix/releases/tag/1.0.3)
[GTNHlib](https://github.com/GTNewHorizons/GTNHLib/releases/tag/0.4.3)
[UniMixins](https://github.com/LegacyModdingMC/UniMixins/releases/tag/0.1.17)

**Comment by kotmatross28729** [comment]
Yeah, that’s how it “should” be. This is a function in angelica - HUDCaching. HUDCaching limits the HUD rendering rate to 20 fps (configurable). So, the reason why HUDCaching is applied in this version, but not applied in the original, is because HUDCaching applied to any [RenderGameOverlayEvent](https://github.com/GTNewHorizons/Angelica/blob/260d57e308080d819b797201a3c5fe57eda330d3/src/mixin/java/com/gtnewhorizons/angelica/mixins/early/angelica/hudcaching/MixinGuiIngame_HUDCaching.java#L17). 

But, the original uses [RenderWorldLastEvent](https://github.com/HostileNetworks/Neat/blob/195506d341fc2af089683564cf16c9797952dc2f/src/main/java/vazkii/neat/HealthBarRenderer.java#L44), therefore HUDCaching doesn't apply to the original


In this fork I replaced `RenderWorldLastEvent` with `RenderGameOverlayEvent` - 8f518ff


This was done because in the original, health bars were actually rendered in the world itself, and were not part of the HUD as such. For this reason, it had problems with shaders, since shaders tried to apply lighting/normals/reflections, etc. to health bars, which, in fact, shouldn't be rendered in the world (Shaders don't try to apply this on HUD elements, for obvious reasons)

If you want to fix it now, disable HUDCaching. 
At best, you need to wait until angelica adds a blacklist for HUDCaching
